# =============================================================================
# ~/.zshrc — mcsquared.ai dev environment
# Generated by Claude Code Environment Setup | March 2026
#
# HOW TO APPLY:
#   1. Back up current: cp ~/.zshrc ~/.zshrc.backup
#   2. Review this file — comment out any section you already handle differently
#   3. Replace: cp zshrc-template.zsh ~/.zshrc
#   4. Reload: source ~/.zshrc
# =============================================================================

# ── PATH: Order matters — first entry wins ────────────────────────────────────
# Rule: most specific/project-level tools first, system last
# pyenv → cargo/uv → homebrew → system

# Apple Silicon Homebrew (if on M1/M2/M3)
eval "$(/opt/homebrew/bin/brew shellenv)" 2>/dev/null || true
# Intel Mac fallback:
# eval "$(/usr/local/bin/brew shellenv)" 2>/dev/null || true

# ── pyenv — Python Version Manager ────────────────────────────────────────────
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
# Note: do NOT add pyenv virtualenv-init unless you use pyenv-virtualenv plugin
# Prefer project-local .venv/ dirs over pyenv virtualenvs

# ── uv — Modern Python Package Manager ────────────────────────────────────────
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"  # uv installs to ~/.local/bin
# uv is used for: uv add, uv run, uv sync, uv lock, uv tool install

# ── gcloud SDK ───────────────────────────────────────────────────────────────
# Claude Code note: installed via `npm install -g @anthropic-ai/claude-code`
# with nvm's default node active. nvm manages the PATH to npm globals automatically.
# Do NOT set npm prefix or npm_config_prefix — both conflict with nvm.
# gcloud SDK
if [[ -f "$HOME/dev/google-cloud-sdk/path.zsh.inc" ]]; then
  source "$HOME/dev/google-cloud-sdk/path.zsh.inc"
fi
if [[ -f "$HOME/dev/google-cloud-sdk/completion.zsh.inc" ]]; then
  source "$HOME/dev/google-cloud-sdk/completion.zsh.inc"
fi

# ── nvm — Node Version Manager ────────────────────────────────────────────────
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

# Auto-use .nvmrc when entering a directory
autoload -U add-zsh-hook
load-nvmrc() {
  local nvmrc_path="$(nvm_find_nvmrc)"
  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$(nvm version)" ]; then
      nvm use
    fi
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# ── direnv — Directory-Scoped Env Vars ────────────────────────────────────────
# Loads .envrc (and .env via dotenv directive) automatically on cd
eval "$(direnv hook zsh)"

# ── fzf — Fuzzy Finder ────────────────────────────────────────────────────────
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type d --hidden --follow --exclude .git"
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border"

# ── zoxide — Smart cd ─────────────────────────────────────────────────────────
eval "$(zoxide init zsh)"
alias cd="z"         # replace cd with z (keeps muscle memory)

# ── bat — Better cat ──────────────────────────────────────────────────────────
alias cat="bat --style=plain"
export BAT_THEME="Catppuccin-mocha"   # or "Dracula"

# ── Starship Prompt ───────────────────────────────────────────────────────────
# MUST be last among prompt/theme setup
eval "$(starship init zsh)"

# ── History Settings ──────────────────────────────────────────────────────────
HISTSIZE=100000
SAVEHIST=100000
HISTFILE="$HOME/.zsh_history"
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE      # Commands prefixed with space are not saved
setopt SHARE_HISTORY          # Share history across terminals
setopt APPEND_HISTORY         # Don't overwrite history
setopt INC_APPEND_HISTORY     # Add to history immediately

# ── Shell Options ─────────────────────────────────────────────────────────────
setopt AUTO_CD                # cd without typing cd
setopt CORRECT                # Spell correction
setopt CORRECT_ALL
setopt NO_CASE_GLOB           # Case-insensitive globbing
setopt EXTENDED_GLOB

# ── Completion ────────────────────────────────────────────────────────────────
autoload -Uz compinit
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
  compinit
else
  compinit -C
fi

# ── Key Bindings ──────────────────────────────────────────────────────────────
bindkey "^[[A" history-search-backward   # Up arrow: history search
bindkey "^[[B" history-search-forward    # Down arrow: history search
bindkey "^[^[[D" backward-word           # Option+Left
bindkey "^[^[[C" forward-word            # Option+Right

# =============================================================================
# PROJECT ALIASES & FUNCTIONS
# =============================================================================

# ── Python ────────────────────────────────────────────────────────────────────
alias venv='python -m venv .venv && source .venv/bin/activate && pip install --upgrade pip'
alias activate='source .venv/bin/activate'
alias deact='deactivate'
alias pip-freeze='pip freeze > requirements.lock'
alias pip-sync='pip install -r requirements.lock'

# ── Shared Envs ───────────────────────────────────────────────────────────────
alias data-tools='source ~/.envs/data-tools/bin/activate && echo "✅ data-tools env active"'
alias gcp-tools='source ~/.envs/gcp-tools/bin/activate && echo "✅ gcp-tools env active"'

# ── Navigation ────────────────────────────────────────────────────────────────
alias dev='cd ~/dev'
alias sandbox='cd ~/dev/sandbox'
alias internal='cd ~/dev/internal'
alias clients='cd ~/dev/clients'
alias templates='cd ~/dev/_templates'

# ── Git ───────────────────────────────────────────────────────────────────────
alias gs='git status -sb'
alias gl='git log --oneline --graph --decorate --all -20'
alias gd='git diff'
alias gds='git diff --staged'
alias ga='git add'
alias gaa='git add -A'
alias gcm='git commit -m'
alias gco='git checkout'
alias gb='git branch -vv'
alias gp='git push'
alias gpl='git pull --rebase'
alias gst='git stash'
alias gstp='git stash pop'
alias gunstage='git reset HEAD --'

# ── Docker ────────────────────────────────────────────────────────────────────
alias dc='docker compose'
alias dcup='docker compose up -d'
alias dcdn='docker compose down'
alias dcl='docker compose logs -f'
alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"'
alias dclean='docker system prune -f && docker volume prune -f'

# ── GCP ───────────────────────────────────────────────────────────────────────
alias gsandbox='gcloud config configurations activate sandbox && echo "☁️  Switched to GCP sandbox"'
alias gprod='gcloud config configurations activate production && echo "☁️  Switched to GCP production"'
alias gcp-project='gcloud config get-value project'
alias gcp-account='gcloud config get-value account'
alias gcp-list-configs='gcloud config configurations list'

# ── Utilities ─────────────────────────────────────────────────────────────────
alias reload='source ~/.zshrc && echo "✅ .zshrc reloaded"'
alias path='echo $PATH | tr ":" "\n" | nl'
alias ports='lsof -i -P -n | grep LISTEN'
alias flushdns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder && echo "✅ DNS flushed"'
alias myip='curl -s https://api.ipify.org && echo'
alias weather='curl -s "wttr.in/?format=3"'
alias sizeof='du -sh'

# ── New Project ───────────────────────────────────────────────────────────────
alias new-project='~/dev/_templates/new-project.sh'

# =============================================================================
# FUNCTIONS
# =============================================================================

# Create new sandbox experiment with date prefix
new-sandbox() {
  local name="${1:-experiment}"
  local dir="$HOME/dev/sandbox/$(date +%Y-%m)-${name}"
  mkdir -p "$dir"
  cd "$dir"
  echo "📁 Created sandbox: $dir"
}

# Quick Python REPL with project context
pyrepl() {
  if [[ -f .venv/bin/python ]]; then
    .venv/bin/python "$@"
  elif [[ -f ../.venv/bin/python ]]; then
    ../.venv/bin/python "$@"
  else
    python "$@"
  fi
}

# Show all venvs in a directory
list-venvs() {
  find "${1:-.}" -name "pyvenv.cfg" -maxdepth 5 2>/dev/null | xargs dirname | sort
}

# Quick HTTP server for current directory
serve() {
  local port="${1:-8080}"
  python -m http.server "$port"
}

# JSON pretty-print with color
json() {
  if [[ -t 0 ]]; then
    cat "$1" | jq .
  else
    jq .
  fi
}

# Git: create branch and push
gbranch() {
  local branch="$1"
  git checkout -b "$branch"
  git push -u origin "$branch"
}

# Find process on port
killport() {
  local port="$1"
  lsof -ti :"$port" | xargs kill -9
  echo "Killed process on port $port"
}

# Docker: shell into running container
dsh() {
  docker exec -it "$1" /bin/bash 2>/dev/null || docker exec -it "$1" /bin/sh
}

# GCP: set project and show current state
gcpset() {
  local project="$1"
  gcloud config set project "$project"
  echo "─────────────────────────────────"
  echo "Project : $(gcloud config get-value project)"
  echo "Account : $(gcloud config get-value account)"
  echo "Region  : $(gcloud config get-value compute/region 2>/dev/null)"
}

# =============================================================================
# ENVIRONMENT VARIABLES (non-secret, safe to commit)
# =============================================================================

# XDG Base Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Language
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Editor
export EDITOR="code --wait"
export VISUAL="code --wait"

# Python: don't create __pycache__ in system Python
export PYTHONDONTWRITEBYTECODE=1

# pip: no warnings about root access
export PIP_REQUIRE_VIRTUALENV=1    # CRITICAL: prevents accidental global pip installs
                                    # Override for shared envs: PIP_REQUIRE_VIRTUALENV=0 pip install ...

# Node: set max memory for large builds
export NODE_OPTIONS="--max-old-space-size=4096"

# Homebrew: no auto-update on every install
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1   # Clean manually with: brew cleanup

# bat colors
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# =============================================================================
# SECRETS: loaded per-project by direnv from .env files
# NEVER put API keys or credentials in this file
# =============================================================================

# ── Load local overrides (machine-specific, gitignored) ──────────────────────
# Put machine-specific settings in ~/.zshrc.local
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
